# Generated by Django 6.0.5 on 2026-05-18 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('hairiness', models.CharField(choices=[('bald', 'Лысый'), ('medium', 'Средний'), ('fluffy', 'Пушистый')], default='medium', max_length=50, verbose_name='Волосатость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Заводчик')),
            ],
        ),
    ]
